package com.example.flipperdroid.model.enums

enum class AdvertisementTarget {
    ADVERTISEMENT_TARGET_UNDEFINED,
    ADVERTISEMENT_TARGET_IOS,
    ADVERTISEMENT_TARGET_SAMSUNG,
    ADVERTISEMENT_TARGET_MICROSOFT,
    ADVERTISEMENT_TARGET_GOOGLE,
}